include: package:lints/recommended.yaml


linter:
  rules:
    avoid_function_literals_in_foreach_calls: false
    prefer_interpolation_to_compose_strings: false

analyzer:
  exclude:
    # - samples/data_class_samples/input_example_data.dart
